name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        You must remove both messenger and facebook then install from here"
    - name: Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: |
          ./release/*.apk
        name: NexAlloy-NonRoot
        tag: all
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
